name: "vmonitor"
title: "VMonitor"
version: "1.0.1"
summary: Server resource monitoring
description: CPU, Disk and Memory monitoring for servers provisioned with vito.team

base: "core18"

parts:
  vmonitor:
    plugin: nodejs
    source: .

apps:
  vmonitor:
    command: vmonitor
    daemon: simple